[package]
name = "colossus-journal-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chacha20poly1305.workspace = true
colossus-contracts.workspace = true
colossus-network.workspace = true
colossus-ports.workspace = true
getrandom.workspace = true
hex.workspace = true
postgres.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio-postgres-rustls.workspace = true
uuid.workspace = true
webpki-roots.workspace = true

[dev-dependencies]
colossus-journal-redb.workspace = true
colossus-memory.workspace = true
colossus-projection.workspace = true
colossus-session.workspace = true
colossus-testkit.workspace = true
colossus-work.workspace = true
colossus-workflow.workspace = true

[lints]
workspace = true
