import type { ManagedMcpDiagnostic, ManagedMcpServer } from "../types";

const toolNames = [
  "add_comment_to_pending_review",
  "add_issue_comment",
  "add_reply_to_pull_request_comment",
  "branch",
  "create_branch",
  "create_or_update_file",
  "create_pull_request",
  "create_repository",
  "delete_file",
  "fork_repository",
  "get_commit",
  "get_file_contents",
  "get_label",
  "get_latest_release",
  "get_me",
  "get_release_by_tag",
  "get_tag",
  "get_team_members",
  "get_teams",
  "issue_read",
  "issue_write",
  "list_branches",
  "list_commits",
  "list_issue_fields",
  "list_issue_types",
  "list_issues",
  "list_pull_requests",
  "list_releases",
  "list_repository_collaborators",
  "list_tags",
  "merge_pull_request",
  "pull_request_read",
  "pull_request_review_write",
  "push_files",
  "request_copilot_review",
  "request_reviewers",
  "run_secret_scanning",
  "search_code",
  "search_commits",
  "search_issues",
  "search_pull_requests",
  "search_repositories",
  "search_users",
  "update_issue_comment",
  "update_pull_request",
];

export function buildMcpHealthFixture(
  server: string,
  transport: ManagedMcpServer["transport"],
): ManagedMcpDiagnostic {
  return {
    server,
    healthy: true,
    tools: toolNames.map((name) => ({
      server,
      name,
      title: null,
      description: null,
    })),
    report: {
      healthy: true,
      elapsedMs: 761,
      stage: "complete",
      failure: null,
      configuration: {
        runtimeVersion: "0.10.10-preview.18",
        transport,
        endpointSha256: transport === "stdio" ? null : "a".repeat(64),
        additionalCaCertificates: transport === "stdio" ? 0 : 2,
        additionalCaSha256: transport === "stdio" ? null : "b".repeat(64),
        directHttp: transport !== "stdio",
        credentialHeaders: transport === "stdio" ? 0 : 1,
        oauth: false,
        allowStateless: false,
        configuredTimeoutMs: 30_000,
      },
    },
  };
}
