[package]
publish = false
name = "colossus-plugins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
colossus-contracts.workspace = true
colossus-journal-redb.workspace = true
colossus-network.workspace = true
colossus-ports.workspace = true
flate2.workspace = true
fs4.workspace = true
futures.workspace = true
hex.workspace = true
http.workspace = true
jsonschema.workspace = true
reqwest.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
sha2.workspace = true
sigstore-verify.workspace = true
tar.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
colossus-windows-native.workspace = true

[lints]
workspace = true
