//! Shared CLI/Desktop MCP health checks through the ordinary effect gateway.

use super::*;
use colossus_contracts::{
    McpDiagnosticCode, McpDiagnosticFailure, McpDiagnosticStage, McpHealthReport,
};
use colossus_mcp::McpDiagnosticCapture;
use std::time::Instant;

/// Released tool inventory plus payload-free evidence from the same discovery attempt.
#[derive(Serialize)]
pub struct McpHealthCheck {
    /// Comparable effective configuration and sanitized failure details.
    pub report: McpHealthReport,
    /// Only tools released by policy; empty if discovery failed.
    pub tools: Vec<McpToolSummary>,
}

impl Runtime {
    /// Diagnose one configured MCP server using its actual credentials, trust, and policy.
    pub async fn mcp_doctor(&self, server: &str) -> McpHealthCheck {
        let started = Instant::now();
        let capture = McpDiagnosticCapture::default();
        let mut configuration = None;
        let result: Result<Vec<McpToolSummary>, RuntimeError> = capture
            .scope(async {
                let catalog = self.plugin_catalog.capture()?;
                let executor = catalog.mcp_executor()?;
                configuration = executor.diagnostic_configuration(server);
                let bound = WorkspaceBoundEffectExecutor::new(
                    self._workspace_lease.identity(),
                    Arc::clone(&executor),
                );
                scope_plugin_catalog(
                    catalog,
                    discover_mcp_tools(
                        self.gateway.as_ref(),
                        executor.as_ref(),
                        &bound,
                        Actor {
                            actor_type: ActorType::User,
                            id: "terminal-user".into(),
                        },
                        ExecutionContext::default(),
                        Some(server),
                    ),
                )
                .await
            })
            .await;
        let (stage, observed_failure) = capture.snapshot();
        let (tools, stage, failure) = match result {
            Ok(tools) => (tools, McpDiagnosticStage::Complete, None),
            Err(error) => {
                let fallback = classify_failure(&error, stage);
                // A denied result never releases even status metadata from that response.
                let failure = if fallback == McpDiagnosticCode::Policy {
                    None
                } else {
                    observed_failure
                }
                .unwrap_or(McpDiagnosticFailure {
                    code: fallback,
                    http_status: None,
                });
                (Vec::new(), stage, Some(failure))
            }
        };
        McpHealthCheck {
            report: McpHealthReport {
                healthy: failure.is_none(),
                elapsed_ms: u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX),
                stage,
                failure,
                configuration,
            },
            tools,
        }
    }
}

fn classify_failure(error: &RuntimeError, stage: McpDiagnosticStage) -> McpDiagnosticCode {
    match error {
        // This exact message is generated by the gateway's deadline, never a server.
        RuntimeError::Gateway(GatewayError::OutcomeUnknown(message))
            if message == "adapter timed out after execution began" =>
        {
            McpDiagnosticCode::Timeout
        }
        RuntimeError::Gateway(
            GatewayError::Safety(_)
            | GatewayError::Denied(_)
            | GatewayError::Approval(_)
            | GatewayError::Policy(_),
        ) => McpDiagnosticCode::Policy,
        RuntimeError::Mcp(_) | RuntimeError::Config(_) => McpDiagnosticCode::Configuration,
        RuntimeError::Gateway(GatewayError::Execution(_) | GatewayError::OutcomeUnknown(_)) => {
            match stage {
                McpDiagnosticStage::Configuration => McpDiagnosticCode::Configuration,
                McpDiagnosticStage::Credentials => McpDiagnosticCode::Credentials,
                McpDiagnosticStage::ClientSetup => McpDiagnosticCode::Transport,
                _ => McpDiagnosticCode::Protocol,
            }
        }
        _ => McpDiagnosticCode::Runtime,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn gateway_denial_and_deadline_remain_distinct_from_protocol_failure() {
        assert_eq!(
            classify_failure(
                &RuntimeError::Gateway(GatewayError::Denied("private policy text".into())),
                McpDiagnosticStage::ValidateResponse
            ),
            McpDiagnosticCode::Policy
        );
        assert_eq!(
            classify_failure(
                &RuntimeError::Gateway(GatewayError::OutcomeUnknown(
                    "adapter timed out after execution began".into()
                )),
                McpDiagnosticStage::Initialize
            ),
            McpDiagnosticCode::Timeout
        );
        assert_eq!(
            classify_failure(
                &RuntimeError::Gateway(GatewayError::Execution("private server text".into())),
                McpDiagnosticStage::Initialize
            ),
            McpDiagnosticCode::Protocol
        );
    }

    #[tokio::test]
    async fn unknown_server_returns_a_sanitized_report_without_network_activity() {
        let workspace = crate::test_support::private_tempdir();
        let mut config = RuntimeConfig::offline_template(workspace.path().join("unused.redb"));
        config.use_ephemeral_storage();
        let runtime = Runtime::open_with_options(
            &config,
            Arc::new(colossus_policy::DenyApproval),
            None,
            RuntimeOpenOptions::for_workspace(workspace.path()).unwrap(),
        )
        .unwrap();
        let check = runtime.mcp_doctor("private-missing-server").await;
        assert!(!check.report.healthy);
        assert!(check.tools.is_empty());
        assert_eq!(
            check.report.failure.as_ref().unwrap().code,
            McpDiagnosticCode::Configuration
        );
        assert!(check.report.configuration.is_none());
        assert!(
            !serde_json::to_string(&check)
                .unwrap()
                .contains("private-missing-server")
        );
    }
}
