use crate::{
    ApiError, ApiErrorReason, ApiResult,
    validation::{MAX_IDENTIFIER_BYTES, MAX_ROLE_BYTES, MAX_TOOL_BYTES, token},
};
use colossus_contracts::{Actor, ActorType, RemoteTraceContext};
use serde::{Deserialize, Serialize};
use std::{
    collections::BTreeSet,
    fmt::{self, Debug, Formatter},
};

const MAX_AUTHORIZATION_ITEMS: usize = 512;

/// Exact public API scope names.
pub mod scopes {
    /// Create and execute agent runs.
    pub const RUNS_EXECUTE: &str = "runs:execute";
    /// Read runs and released run updates.
    pub const RUNS_READ: &str = "runs:read";
    /// Cancel runs owned by the caller.
    pub const RUNS_CONTROL: &str = "runs:control";
    /// Respond to ordinary user prompts.
    pub const PROMPTS_RESPOND: &str = "prompts:respond";
    /// Respond to effect approval requests.
    pub const APPROVALS_RESPOND: &str = "approvals:respond";
    /// Read caller-owned released artifact metadata and bytes.
    pub const ARTIFACTS_READ: &str = "artifacts:read";
    /// Reserve and upload caller-owned bounded artifacts.
    pub const ARTIFACTS_WRITE: &str = "artifacts:write";
}

/// Validated exact API scope.
#[derive(Clone, Eq, Ord, PartialEq, PartialOrd, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ApiScope(String);

impl ApiScope {
    /// Validate one canonical scope.
    pub fn new(value: impl Into<String>) -> ApiResult<Self> {
        let value = value.into();
        token(&value, "scope", MAX_IDENTIFIER_BYTES)?;
        Ok(Self(value))
    }

    /// Return the canonical scope value.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Debug for ApiScope {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.debug_tuple("ApiScope").field(&self.0).finish()
    }
}

impl TryFrom<String> for ApiScope {
    type Error = ApiError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<ApiScope> for String {
    fn from(value: ApiScope) -> Self {
        value.0
    }
}

/// Validated transport request identifier.
#[derive(Clone, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct RequestId(String);

impl RequestId {
    /// Validate a request identifier generated by the server or transport adapter.
    pub fn new(value: impl Into<String>) -> ApiResult<Self> {
        let value = value.into();
        token(&value, "request_id", MAX_IDENTIFIER_BYTES)?;
        Ok(Self(value))
    }

    /// Return the validated identifier.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for RequestId {
    type Error = ApiError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<RequestId> for String {
    fn from(value: RequestId) -> Self {
        value.0
    }
}

/// Validated caller-selected key for one idempotent operation.
#[derive(Clone, Eq, PartialEq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct IdempotencyKey(String);

impl IdempotencyKey {
    /// Validate an idempotency key.
    pub fn new(value: impl Into<String>) -> ApiResult<Self> {
        let value = value.into();
        token(&value, "idempotency_key", MAX_IDENTIFIER_BYTES)?;
        Ok(Self(value))
    }

    /// Return the exact key for hashing and transport serialization.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Debug for IdempotencyKey {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str("IdempotencyKey([REDACTED])")
    }
}

impl TryFrom<String> for IdempotencyKey {
    type Error = ApiError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<IdempotencyKey> for String {
    fn from(value: IdempotencyKey) -> Self {
        value.0
    }
}

/// How the authenticated application is hosted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ApplicationKind {
    /// An enrolled client of the shared daemon.
    Enrolled,
    /// An application supervising an isolated Colossus sidecar.
    Sidecar,
    /// Trusted Rust code embedding an isolated runtime.
    Embedded,
}

/// Authenticated application identity and immutable authorization ceilings.
///
/// This type intentionally has no deserialization implementation. A server transport
/// must build it only after verifying a credential; it must never deserialize it from a
/// client request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApplicationPrincipal {
    application_id: String,
    credential_id: String,
    kind: ApplicationKind,
    scopes: BTreeSet<ApiScope>,
    allowed_roles: BTreeSet<String>,
    allowed_tools: BTreeSet<String>,
}

impl ApplicationPrincipal {
    /// Construct a principal after credential verification.
    ///
    /// Empty role or tool sets deny every role or tool. They never mean unrestricted.
    pub fn authenticated(
        application_id: impl Into<String>,
        credential_id: impl Into<String>,
        kind: ApplicationKind,
        scopes: impl IntoIterator<Item = ApiScope>,
        allowed_roles: impl IntoIterator<Item = String>,
        allowed_tools: impl IntoIterator<Item = String>,
    ) -> ApiResult<Self> {
        let application_id = application_id.into();
        let credential_id = credential_id.into();
        token(&application_id, "application_id", MAX_IDENTIFIER_BYTES)?;
        let application_token = application_id.strip_prefix("app:").ok_or_else(|| {
            ApiError::invalid(
                ApiErrorReason::InvalidArgument,
                "application_id",
                "application_id must use the app:<token> namespace",
            )
        })?;
        token(
            application_token,
            "application_id",
            MAX_IDENTIFIER_BYTES - "app:".len(),
        )?;
        token(&credential_id, "credential_id", MAX_IDENTIFIER_BYTES)?;
        let scopes = scopes
            .into_iter()
            .take(MAX_AUTHORIZATION_ITEMS.saturating_add(1))
            .collect::<BTreeSet<_>>();
        if scopes.len() > MAX_AUTHORIZATION_ITEMS {
            return Err(ApiError::invalid(
                ApiErrorReason::InvalidArgument,
                "scopes",
                format!("scopes must contain at most {MAX_AUTHORIZATION_ITEMS} entries"),
            ));
        }
        let allowed_roles = validate_constraints(allowed_roles, "allowed_role", MAX_ROLE_BYTES)?;
        let allowed_tools = validate_constraints(allowed_tools, "allowed_tool", MAX_TOOL_BYTES)?;
        Ok(Self {
            application_id,
            credential_id,
            kind,
            scopes,
            allowed_roles,
            allowed_tools,
        })
    }

    /// Stable authenticated application identifier.
    pub fn application_id(&self) -> &str {
        &self.application_id
    }

    /// Credential identifier, never credential material.
    pub fn credential_id(&self) -> &str {
        &self.credential_id
    }

    /// Hosting class associated with the credential.
    pub fn kind(&self) -> ApplicationKind {
        self.kind
    }

    /// Return whether the exact scope was granted.
    pub fn has_scope(&self, scope: &str) -> bool {
        self.scopes
            .iter()
            .any(|candidate| candidate.as_str() == scope)
    }

    /// Iterate exact authenticated scopes in deterministic order.
    pub fn scopes(&self) -> impl ExactSizeIterator<Item = &ApiScope> {
        self.scopes.iter()
    }

    /// Return whether a role is inside the authenticated ceiling.
    pub fn allows_role(&self, role: &str) -> bool {
        self.allowed_roles.contains(role)
    }

    /// Iterate allowed logical roles in deterministic order.
    pub fn allowed_roles(&self) -> impl ExactSizeIterator<Item = &str> {
        self.allowed_roles.iter().map(String::as_str)
    }

    /// Return whether a tool is inside the authenticated ceiling.
    pub fn allows_tool(&self, tool: &str) -> bool {
        self.allowed_tools.contains(tool)
    }

    /// Iterate allowed tools in deterministic order.
    ///
    /// An empty iterator means deny all, never unrestricted.
    pub fn allowed_tools(&self) -> impl ExactSizeIterator<Item = &str> {
        self.allowed_tools.iter().map(String::as_str)
    }

    /// Create durable journal attribution without credential material.
    pub fn actor(&self) -> Actor {
        Actor {
            actor_type: ActorType::Application,
            id: self.application_id.clone(),
        }
    }
}

/// Server-created caller identity and correlation metadata for one request.
///
/// It is deliberately not serializable or deserializable. Public request DTOs do not
/// contain an actor, credential identifier, or scope set.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CallerContext {
    principal: ApplicationPrincipal,
    request_id: RequestId,
    remote_trace_context: Option<RemoteTraceContext>,
}

impl CallerContext {
    /// Bind an authenticated principal to one server-generated request identifier.
    pub fn authenticated(principal: ApplicationPrincipal, request_id: RequestId) -> Self {
        Self {
            principal,
            request_id,
            remote_trace_context: None,
        }
    }

    /// Attach transport-validated W3C Trace Context for durable asynchronous work.
    pub fn with_remote_trace_context(mut self, context: Option<RemoteTraceContext>) -> Self {
        self.remote_trace_context = context;
        self
    }

    /// Authenticated application principal.
    pub fn principal(&self) -> &ApplicationPrincipal {
        &self.principal
    }

    /// Correlation identifier for this API request.
    pub fn request_id(&self) -> &RequestId {
        &self.request_id
    }

    /// Validated remote parent context, excluding baggage.
    pub fn remote_trace_context(&self) -> Option<&RemoteTraceContext> {
        self.remote_trace_context.as_ref()
    }

    /// Durable application actor derived only from authenticated server state.
    pub fn actor(&self) -> Actor {
        self.principal.actor()
    }

    /// Enforce an exact scope and attach this request's correlation identifier on denial.
    pub fn require_scope(&self, scope: &str) -> ApiResult<()> {
        if self.principal.has_scope(scope) {
            return Ok(());
        }
        Err(ApiError::permission_denied(
            ApiErrorReason::ScopeDenied,
            "the authenticated application is not allowed to perform this operation",
        )
        .with_correlation_id(self.request_id.clone()))
    }

    /// Enforce the authenticated role ceiling.
    pub fn require_role(&self, role: &str) -> ApiResult<()> {
        if self.principal.allows_role(role) {
            return Ok(());
        }
        Err(ApiError::permission_denied(
            ApiErrorReason::RoleDenied,
            "the authenticated application is not allowed to use this role",
        )
        .with_correlation_id(self.request_id.clone()))
    }

    /// Enforce the authenticated tool ceiling.
    pub fn require_tool(&self, tool: &str) -> ApiResult<()> {
        if self.principal.allows_tool(tool) {
            return Ok(());
        }
        Err(ApiError::permission_denied(
            ApiErrorReason::ToolDenied,
            "the authenticated application is not allowed to use this tool",
        )
        .with_correlation_id(self.request_id.clone()))
    }
}

fn validate_constraints(
    values: impl IntoIterator<Item = String>,
    field: &str,
    max_bytes: usize,
) -> ApiResult<BTreeSet<String>> {
    let values = values
        .into_iter()
        .take(MAX_AUTHORIZATION_ITEMS.saturating_add(1))
        .map(|value| {
            token(&value, field, max_bytes)?;
            Ok(value)
        })
        .collect::<ApiResult<BTreeSet<_>>>()?;
    if values.len() > MAX_AUTHORIZATION_ITEMS {
        return Err(ApiError::invalid(
            ApiErrorReason::InvalidArgument,
            field,
            format!("{field} must contain at most {MAX_AUTHORIZATION_ITEMS} entries"),
        ));
    }
    Ok(values)
}
