[package]
name = "colossus-windows-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_JobObjects",
    "Win32_System_Pipes",
    "Win32_System_Rpc",
    "Win32_System_Threading",
] }

[lints.clippy]
all = { level = "deny", priority = -1 }
missing_safety_doc = "deny"
