[package]
name = "colossus-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
colossus-contracts.workspace = true
colossus-ports.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
colossus-testkit.workspace = true

[lints]
workspace = true
